version: '3.2'

services:
  node:
    image: queuesub
    restart: always
    build:
      context: ./
      dockerfile: ./node.docker
    container_name: queuesubnode
    ports:
      - '8082:8082'
    volumes:
      - ./node-app:/application
    env_file: ./node-app/app.env
    command: ['bash', 'start.sh']
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
